config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('identification/', include('identification.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

identification/urls.py
from django.urls import path
from . import views

app_name = 'identification'

urlpatterns = [
    path('', views.IdentificationIndexView.as_view(), name='index'),
    path('result/', views.IdentificationResultView.as_view(), name='result')
]

identification/models.py
from django.db import models

# Create your models here.

identification/views.py
import os
from tensorflow.keras.models import load_model
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.core.files.storage import FileSystemStorage
from PIL import Image
import numpy as np
from django.conf import settings

ALLOWED_EXTENSIONS = {"png", "jpg", "jpeg", "gif"}

labels = ["飛行機","自動車", "鳥", "猫", "鹿", "犬", "カエル", "馬", "船", "トラック"]
n_class = len(labels)
img_size = 32
n_result = 3  # 上位3つの結果を表示

class IdentificationIndexView(TemplateView):
    def get(self, request, *args, **kwargs):
        return render(request, "identification/index.html")


class IdentificationResultView(TemplateView):
    def get(self, request, *args, **kwargs):
        return redirect("/identification")


    def post(self, request, *args, **kwargs):
        # ファイルの存在と形式を確認
        file = request.FILES
        if len(file) == 0:
            context = {
                'msg' : "File doesn't exist!"
            }
            return render(request, "identification/index.html", context)
        filename = request.FILES['uploadFile']
        str_filename = str(filename)

        if not self.allowed_file(str_filename):
            context = {
                'msg' : str_filename + ": File not allowed!"
            }
            return render(request, "identification/index.html", context)

        # ファイルの保存
        fs = FileSystemStorage()
        fs.save(filename.name, filename)
        
        filepath = os.path.join(settings.MEDIA_ROOT, str_filename)

        # 画像の読み込み
        image = Image.open(filepath)
        image = image.convert("RGB")
        image = image.resize((img_size, img_size))
        x = np.array(image, dtype=float)
        x = x.reshape(1, img_size, img_size, 3) / 255

        # 予測
        model = load_model("/Applications/project/image_identification/identification/image_classifier.h5")
        y = model.predict(x)[0]
        sorted_idx = np.argsort(y)[::-1]  # 降順でソート
        result = ""
        for i in range(n_result):
            idx = sorted_idx[i]
            ratio = y[idx]
            label = labels[idx]
            result += "<p>" + str(round(ratio*100, 1)) + "%の確率で" + label + "です。</p>"
            context = {
                "filepath" : settings.MEDIA_URL + str_filename,
                "result"   : result
            }
        return render(request, "identification/result.html", context)
        
    def allowed_file(self, filename):
        return "." in filename and filename.rsplit(".", 1)[1].lower() in ALLOWED_EXTENSIONS
        
    

templates/identification/index.html
{% extends "./layout.html" %}
{% block title %}画像分類{% endblock %}
{% block content %}
    <div class="container">
        <div class="col content">
            <h1>画像分類</h1>
            <form method="post", enctype="multipart/form-data", action="{% url 'identification:result' %}">
                {% csrf_token %}
                {% if msg %}
                    <div>{{ msg }}</div>
                {% endif %}
                <input name="uploadFile" type="file">
                <input type="submit", value="判定">
            </form>
        </div>
    </div>
{% endblock %}

templates/identification/layout.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='slim' %}
<html>
  <head>
    <meta charset="UTF=8">
    <title>画像分類</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <style media="screen">
      .content {
        width: 100%;
        text-align: center;
      }
      .content h1 {
        width: 100%;
        margin-top: 25px;
      }
      .content form {
        width: 100%;
      }
      .content p {
        font-size: 20px;
      }
    </style>
  </head>
  <body>
    {% block content %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  </body>
</html>

templates/identification/result.html
{% extends "./layout.html" %}
{% block content %}
<div class="container">
  <div class="col content">
    <h1>判定結果</h1>
    {{result| safe}}
    <img src="{{ filepath }}"><br>
    <form method="get" action="/identification">
      <button class="submit">戻る</button>
    </form>
  </div>
</div>
{% endblock %}